// Auth Dispatch States
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";
export const AUTHENTICATED_SUCCESS = "AUTHENTICATED_SUCCESS";
export const AUTHENTICATED_FAIL = "AUTHENTICATED_FAIL";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";

// Profile Dispatch States
export const LOAD_USER_PROFILE_SUCCESS = "LOAD_USER_PROFILE_SUCCESS";
export const LOAD_USER_PROFILE_FAIL = "LOAD_USER_PROFILE_FAIL";
export const UPDATE_USER_PROFILE_SUCCESS = "UPDATE_USER_PROFILE_SUCCESS";
export const UPDATE_USER_PROFILE_FAIL = "UPDATE_USER_PROFILE_FAIL";

// Admin Dispatch States
export const GET_STUDENT_DATA_SUCCESS = "GET_STUDENT_DATA_SUCCESS";
export const GET_STUDENT_DATA_FAILURE = "GET_STUDENT_DATA_FAILURE";
export const DELETE_USER_ADMIN_SUCCESS = "DELETE_USER_ADMIN_SUCCESS";
export const DELETE_USER_ADMIN_FAIL = "DELETE_USER_ADMIN_FAIL";
export const GET_ADMIN_DATA_SUCCESS = "GET_ADMIN_DATA_SUCCESS";
export const GET_ADMIN_DATA_FAILURE = "GET_ADMIN_DATA_FAILURE";
export const REMOVE_ADMIN_SUCCESS = "REMOVE_ADMIN_SUCCESS";
export const REMOVE_ADMIN_FAILURE = "REMOVE_ADMIN_FAILURE";
export const ADD_ADMIN_SUCCESS = "ADD_ADMIN_SUCCESS";
export const ADD_ADMIN_FAILURE = "ADD_ADMIN_FAILURE";

// Admin actions for dictionaries
export const ADD_DICTIONARY_SUCCESS = "ADD_DICTIONARY_SUCCESS";
export const ADD_DICTIONARY_FAILURE = "ADD_DICTIONARY_FAILURE";
export const ADD_WORD_SUCCESS = "ADD_WORD_SUCCESS";
export const ADD_WORD_FAILURE = "ADD_WORD_FAILURE";
export const REMOVE_WORD_FAILURE = "REMOVE_WORD_FAILURE";
export const REMOVE_WORD_SUCCESS = "REMOVE_WORD_SUCCESS";
export const CLOSE_VIEW_DICTIONARY_ADMIN = "CLOSE_VIEW_DICTIONARY_ADMIN";
export const EDIT_WORD_SUCCESS = "EDIT_WORD_SUCCESS";
export const EDIT_WORD_FAIL = "EDIT_WORD_FAIL";
export const REMOVE_WORD_FROM_REDUCER_STATE = "REMOVE_WORD_FROM_REDUCER_STATE"
export const UPDATE_WORD_IN_REDUCER_STATE = "UPDATE_WORD_IN_REDUCER_STATE"

// Process of choosing dictionary, language and modules
export const SELECT_DICTIONARY = "SELECT_DICTIONARY";
export const SELECT_DICTIONARY_FAIL = "SELECT_DICTIONARY_FAIL";
export const SELECT_MODE = "SELECT_MODE";
export const SELECT_MODE_FAIL = "SELECT_MODE_FAIL";
export const START_LEARNING = "START_LEARNING";
export const START_LEARNING_FAIL = "START_LEARNING_FAIL";
export const GET_DICTIONARIES = "GET_DICTIONARIES";
export const GET_DICTIONARIES_FAIL = "GET_DICTIONARIES_FAIL";
export const SELECT_LANGUAGE = "SELECT_LANGUAGE";
export const CLOSE_ADDING_WORD = "CLOSE_ADDING_WORD";
export const SELECT_LANGUAGE_VIEW = "SELECT_LANGUAGE_VIEW";
export const SELECT_DICTIONARY_VIEW = "SELECT_DICTIONARY_VIEW";
export const CLOSE_VIEW_DICTIONARY = "CLOSE_VIEW_DICTIONARY";
export const GET_DICTIONARY_WORDS_SUCCESS = "GET_DICCTIONARY_WORDS_SUCCESS";
export const GET_DICTIONARY_WORDS_FAIL = "GET_DICCTIONARY_WORDS_FAIL";
export const FINISH_LEARNING = "FINISH_LEARNING";

// Autofill action
export const AUTOFILL_SUGGESTIONS_FROM_API = "AUTOFILL_SUGGESTIONS_FROM_API";
export const CACHE_AUTOFILL_SUGGESTIONS = "CACHE_AUTOFILL_SUGGESTIONS";

export const AUTOFILL_SUGGESTIONS_FROM_CACHE =
  "AUTOFILL_SUGGESTIONS_FROM_CACHE";
export const UPDATE_AUTOFILL_DESCRIPTION = "UPDATE_AUTOFILL_DESCRIPTION";

export const RESET_AUTOFILL = "RESET_AUTOFILL";

// Random words action
export const UPDATE_RANDOM_WORDS = "UPDATE_RANDOM_WORDS";

// mode12 action
export const GET_SESSION = "GET_SESSION";
export const GET_SESSION_FAIL = "GET_SESSION_FAIL";
export const INITIALIZE_SESSION = "INITIALIZE_SESSION";
export const INITIALIZE_SESSION_FAIL = "INITIALIZE_SESSION_FAIL";
export const ANSWER_QUESTION = "ANSWER_QUESTION";
export const ANSWER_QUESTION_FAIL = "ANSWER_QUESTION_FAIL";
export const DESTROY_SESSION = "DESTROY_SESSION";
export const DESTROY_SESSION_FAIL = "DESTROY_SESSION_FAIL";
export const GET_AUDIO_FILE_SUCCESS = "GET_AUDIO_FILE_SUCCESS";
export const GET_AUDIO_FILE_FAIL = "GET_AUDIO_FILE_FAIL";
