// Auth Dispatch States
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';
export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS';
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL';

// Profile Dispatch States
export const LOAD_USER_PROFILE_SUCCESS = 'LOAD_USER_PROFILE_SUCCESS';
export const LOAD_USER_PROFILE_FAIL = 'LOAD_USER_PROFILE_FAIL';
export const UPDATE_USER_PROFILE_SUCCESS = 'UPDATE_USER_PROFILE_SUCCESS';
export const UPDATE_USER_PROFILE_FAIL = 'UPDATE_USER_PROFILE_FAIL';

// Admin Dispatch States
export const GET_STUDENT_DATA_SUCCESS = 'GET_STUDENT_DATA_SUCCESS';
export const GET_STUDENT_DATA_FAILURE = 'GET_STUDENT_DATA_FAILURE';
export const DELETE_USER_ADMIN_SUCCESS = 'DELETE_USER_ADMIN_SUCCESS';
export const DELETE_USER_ADMIN_FAIL = 'DELETE_USER_ADMIN_FAIL';
export const GET_ADMIN_DATA_SUCCESS = 'GET_ADMIN_DATA_SUCCESS';
export const GET_ADMIN_DATA_FAILURE = 'GET_ADMIN_DATA_FAILURE';
export const REMOVE_ADMIN_SUCCESS = 'REMOVE_ADMIN_SUCCESS';
export const REMOVE_ADMIN_FAILURE = 'REMOVE_ADMIN_FAILURE';
export const ADD_ADMIN_SUCCESS = 'ADD_ADMIN_SUCCESS';
export const ADD_ADMIN_FAILURE = 'ADD_ADMIN_FAILURE';
