# Generated by Django 4.1.13 on 2023-12-07 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='customuser_ptr',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='permission_level',
        ),
        migrations.DeleteModel(
            name='Administrator',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
