# Generated by Django 4.1.13 on 2023-12-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_dictionary_dict_name_remove_word_parent_dict_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='audio_bytes',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='language',
            field=models.CharField(default='en', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='word',
            name='word_type',
            field=models.CharField(default='verb', max_length=32),
            preserve_default=False,
        ),
    ]
