# Generated by Django 4.1.13 on 2023-12-14 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_student_customuser_ptr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('answers_correct', models.IntegerField()),
                ('answers_incorrect', models.IntegerField()),
                ('mode', models.CharField(max_length=3)),
            ],
            options={
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('dict_name', models.CharField(max_length=64, unique=True)),
                ('language', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('word_str', models.TextField()),
                ('cro_translation', models.TextField()),
                ('definition', models.TextField()),
                ('parent_dict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.dictionary')),
            ],
        ),
        migrations.CreateModel(
            name='StudyData',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
