# Generated by Django 4.1.13 on 2023-12-26 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_word_audio_bytes_word_language_word_word_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dictionary',
            unique_together=set(),
        ),
    ]
