# Generated by Django 4.1.13 on 2023-12-28 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_dictionary_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
