# Generated by Django 4.1.13 on 2024-01-03 22:10

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_delete_question_delete_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyDataWords',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('hidden_for', models.IntegerField()),
                ('_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.word')),
            ],
        ),
        migrations.CreateModel(
            name='StudyDataDictionary',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('_dict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.dictionary')),
                ('words', models.ManyToManyField(to='main.studydatawords')),
            ],
        ),
        migrations.AddField(
            model_name='studydata',
            name='data',
            field=models.ManyToManyField(to='main.studydatadictionary'),
        ),
    ]
