# Generated by Django 4.1.13 on 2024-01-03 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_studydatawords_studydatadictionary_studydata_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studydata',
            name='data',
        ),
        migrations.RemoveField(
            model_name='studydatadictionary',
            name='words',
        ),
        migrations.AddField(
            model_name='studydatadictionary',
            name='study_data',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.studydata'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studydatawords',
            name='study_data_dictionary',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.studydatadictionary'),
            preserve_default=False,
        ),
    ]
